#!/bin/bash
sed -i 's/PIN_RESET/PIN_RESET, EXPENSE_CREATED, EXPENSE_DELETED, DRAWING_CREATED, KHATA_CUSTOMER_CREATED, KHATA_PAYMENT_RECORDED, OPENING_BALANCE_SET, CATALOG_IMPORTED/g' app/src/main/java/com/boikhata/domain/model/Enums.kt
