package com.boikhata.domain.model

enum class Role {
    OWNER, MANAGER, SALES, ACCOUNTANT
}

enum class LicenseState {
    ACTIVE, GRACE, SOFT_LOCKED, SUSPENDED
}

enum class AuditAction {
    LOGIN_SUCCESS, LOGIN_FAIL, ROLE_SWITCH, USER_CREATED, USER_DISABLED, PIN_RESET, EXPENSE_CREATED, EXPENSE_DELETED, DRAWING_CREATED, KHATA_CUSTOMER_CREATED, KHATA_PAYMENT_RECORDED, OPENING_BALANCE_SET, CATALOG_IMPORTED, BILL_CREATED, BILL_VOID
}
